version: '3.8'

# E2E test infrastructure for authz testing
# Usage: podman-compose -f docker-compose.e2e.yml up -d

services:
  dynamodb-local:
    image: docker.io/amazon/dynamodb-local:latest
    container_name: rosa-dynamodb-local
    ports:
      - "8180:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]

  cedar-agent:
    image: docker.io/permitio/cedar-agent:latest
    container_name: rosa-cedar-agent
    ports:
      - "8181:8180"
